// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://avyntzcuanewmxiwwzdw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF2eW50emN1YW5ld214aXd3emR3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5NjAxMzksImV4cCI6MjA2NjUzNjEzOX0.gmuE__zL5nDFZFCRM5WoOm5Myftt47hXp5VbWukXdCQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);